sudo: false
language: node_js
node_js:
 - "stable"
services:
  - postgresql
before_script:
  - yarn global add nyc
  - psql -c 'create database jubilee_test;' -U postgres
script:
 - npm run coveralls
notifications:
  email: false
