language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
services:
  - postgresql
before_script:
  - psql -c 'create database jubilee_ test;' -U postgres
script:
  - npm i -g sequelize-cli
  - npm install
  - npm test
  - npm run coveralls
notifications:
  email: false
